apiVersion: v1
kind: Service
metadata:
  name: person-api
  namespace: person
  labels:
    app: person-api
spec:
  ports:
    - name: http
      port: 8081
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: person-api
